/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as AuthedAttendanceRouteImport } from './routes/_authed/attendance'
import { Route as AuthedDevicesRouteImport } from './routes/_authed/devices'
import { Route as AuthedInventoryRouteImport } from './routes/_authed/inventory'
import { Route as AuthedMembersRouteImport } from './routes/_authed/members'
import { Route as AuthedPlansRouteImport } from './routes/_authed/plans'
import { Route as AuthedProductsRouteImport } from './routes/_authed/products'
import { Route as AuthedTransactionsRouteImport } from './routes/_authed/transactions'
import { Route as AuthedWorkersRouteImport } from './routes/_authed/workers'
import { Route as AuthedOrdersIndexRouteImport } from './routes/_authed/orders.index'
import { Route as AuthedOrdersNewRouteImport } from './routes/_authed/orders.new'

const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAttendanceRoute = AuthedAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDevicesRoute = AuthedDevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedInventoryRoute = AuthedInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedMembersRoute = AuthedMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPlansRoute = AuthedPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedProductsRoute = AuthedProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedTransactionsRoute = AuthedTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedWorkersRoute = AuthedWorkersRouteImport.update({
  id: '/workers',
  path: '/workers',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedOrdersIndexRoute = AuthedOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedOrdersNewRoute = AuthedOrdersNewRouteImport.update({
  id: '/orders/new',
  path: '/orders/new',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/sign-in': typeof SignInRoute
  '/attendance': typeof AuthedAttendanceRoute
  '/devices': typeof AuthedDevicesRoute
  '/inventory': typeof AuthedInventoryRoute
  '/members': typeof AuthedMembersRoute
  '/plans': typeof AuthedPlansRoute
  '/products': typeof AuthedProductsRoute
  '/transactions': typeof AuthedTransactionsRoute
  '/workers': typeof AuthedWorkersRoute
  '/orders/new': typeof AuthedOrdersNewRoute
  '/orders/': typeof AuthedOrdersIndexRoute
}
export interface FileRoutesByTo {
  '/sign-in': typeof SignInRoute
  '/attendance': typeof AuthedAttendanceRoute
  '/devices': typeof AuthedDevicesRoute
  '/inventory': typeof AuthedInventoryRoute
  '/members': typeof AuthedMembersRoute
  '/plans': typeof AuthedPlansRoute
  '/products': typeof AuthedProductsRoute
  '/transactions': typeof AuthedTransactionsRoute
  '/workers': typeof AuthedWorkersRoute
  '/': typeof AuthedIndexRoute
  '/orders/new': typeof AuthedOrdersNewRoute
  '/orders': typeof AuthedOrdersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/_authed/attendance': typeof AuthedAttendanceRoute
  '/_authed/devices': typeof AuthedDevicesRoute
  '/_authed/inventory': typeof AuthedInventoryRoute
  '/_authed/members': typeof AuthedMembersRoute
  '/_authed/plans': typeof AuthedPlansRoute
  '/_authed/products': typeof AuthedProductsRoute
  '/_authed/transactions': typeof AuthedTransactionsRoute
  '/_authed/workers': typeof AuthedWorkersRoute
  '/_authed/': typeof AuthedIndexRoute
  '/_authed/orders/new': typeof AuthedOrdersNewRoute
  '/_authed/orders/': typeof AuthedOrdersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/attendance'
    | '/devices'
    | '/inventory'
    | '/members'
    | '/plans'
    | '/products'
    | '/transactions'
    | '/workers'
    | '/orders/new'
    | '/orders/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/sign-in'
    | '/attendance'
    | '/devices'
    | '/inventory'
    | '/members'
    | '/plans'
    | '/products'
    | '/transactions'
    | '/workers'
    | '/'
    | '/orders/new'
    | '/orders'
  id:
    | '__root__'
    | '/_authed'
    | '/sign-in'
    | '/_authed/attendance'
    | '/_authed/devices'
    | '/_authed/inventory'
    | '/_authed/members'
    | '/_authed/plans'
    | '/_authed/products'
    | '/_authed/transactions'
    | '/_authed/workers'
    | '/_authed/'
    | '/_authed/orders/new'
    | '/_authed/orders/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  SignInRoute: typeof SignInRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/attendance': {
      id: '/_authed/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AuthedAttendanceRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/devices': {
      id: '/_authed/devices'
      path: '/devices'
      fullPath: '/devices'
      preLoaderRoute: typeof AuthedDevicesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/inventory': {
      id: '/_authed/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AuthedInventoryRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/members': {
      id: '/_authed/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof AuthedMembersRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/plans': {
      id: '/_authed/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof AuthedPlansRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/products': {
      id: '/_authed/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AuthedProductsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/transactions': {
      id: '/_authed/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof AuthedTransactionsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/workers': {
      id: '/_authed/workers'
      path: '/workers'
      fullPath: '/workers'
      preLoaderRoute: typeof AuthedWorkersRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/orders/': {
      id: '/_authed/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof AuthedOrdersIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/orders/new': {
      id: '/_authed/orders/new'
      path: '/orders/new'
      fullPath: '/orders/new'
      preLoaderRoute: typeof AuthedOrdersNewRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedAttendanceRoute: typeof AuthedAttendanceRoute
  AuthedDevicesRoute: typeof AuthedDevicesRoute
  AuthedInventoryRoute: typeof AuthedInventoryRoute
  AuthedMembersRoute: typeof AuthedMembersRoute
  AuthedPlansRoute: typeof AuthedPlansRoute
  AuthedProductsRoute: typeof AuthedProductsRoute
  AuthedTransactionsRoute: typeof AuthedTransactionsRoute
  AuthedWorkersRoute: typeof AuthedWorkersRoute
  AuthedIndexRoute: typeof AuthedIndexRoute
  AuthedOrdersNewRoute: typeof AuthedOrdersNewRoute
  AuthedOrdersIndexRoute: typeof AuthedOrdersIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedAttendanceRoute: AuthedAttendanceRoute,
  AuthedDevicesRoute: AuthedDevicesRoute,
  AuthedInventoryRoute: AuthedInventoryRoute,
  AuthedMembersRoute: AuthedMembersRoute,
  AuthedPlansRoute: AuthedPlansRoute,
  AuthedProductsRoute: AuthedProductsRoute,
  AuthedTransactionsRoute: AuthedTransactionsRoute,
  AuthedWorkersRoute: AuthedWorkersRoute,
  AuthedIndexRoute: AuthedIndexRoute,
  AuthedOrdersNewRoute: AuthedOrdersNewRoute,
  AuthedOrdersIndexRoute: AuthedOrdersIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  SignInRoute: SignInRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
