/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as AuthedAttendanceRouteImport } from './routes/_authed/attendance'
import { Route as AuthedDevicesRouteImport } from './routes/_authed/devices'
import { Route as AuthedMembersRouteImport } from './routes/_authed/members'
import { Route as AuthedPlansRouteImport } from './routes/_authed/plans'
import { Route as AuthedSettingsRouteImport } from './routes/_authed/settings'
import { Route as AuthedTransactionsRouteImport } from './routes/_authed/transactions'
import { Route as AuthedWorkersRouteImport } from './routes/_authed/workers'
import { Route as AuthedInventoryIndexRouteImport } from './routes/_authed/inventory.index'
import { Route as AuthedInventoryHistoryRouteImport } from './routes/_authed/inventory.history'
import { Route as AuthedInventorySuppliersRouteImport } from './routes/_authed/inventory.suppliers'
import { Route as AuthedOrdersIndexRouteImport } from './routes/_authed/orders.index'
import { Route as AuthedOrdersNewRouteImport } from './routes/_authed/orders.new'
import { Route as AuthedProductsIndexRouteImport } from './routes/_authed/products.index'
import { Route as AuthedProductsIngredientsRouteImport } from './routes/_authed/products.ingredients'
import { Route as AuthedProductsCombosIndexRouteImport } from './routes/_authed/products.combos.index'
import { Route as AuthedProductsCombosComboIdRouteImport } from './routes/_authed/products.combos.$comboId'
import { Route as AuthedProductsCombosNewRouteImport } from './routes/_authed/products.combos.new'

const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAttendanceRoute = AuthedAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDevicesRoute = AuthedDevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedMembersRoute = AuthedMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPlansRoute = AuthedPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsRoute = AuthedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedTransactionsRoute = AuthedTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedWorkersRoute = AuthedWorkersRouteImport.update({
  id: '/workers',
  path: '/workers',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedInventoryIndexRoute = AuthedInventoryIndexRouteImport.update({
  id: '/inventory/',
  path: '/inventory/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedInventoryHistoryRoute = AuthedInventoryHistoryRouteImport.update({
  id: '/inventory/history',
  path: '/inventory/history',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedInventorySuppliersRoute =
  AuthedInventorySuppliersRouteImport.update({
    id: '/inventory/suppliers',
    path: '/inventory/suppliers',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedOrdersIndexRoute = AuthedOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedOrdersNewRoute = AuthedOrdersNewRouteImport.update({
  id: '/orders/new',
  path: '/orders/new',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedProductsIndexRoute = AuthedProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedProductsIngredientsRoute =
  AuthedProductsIngredientsRouteImport.update({
    id: '/products/ingredients',
    path: '/products/ingredients',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedProductsCombosIndexRoute =
  AuthedProductsCombosIndexRouteImport.update({
    id: '/products/combos/',
    path: '/products/combos/',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedProductsCombosComboIdRoute =
  AuthedProductsCombosComboIdRouteImport.update({
    id: '/products/combos/$comboId',
    path: '/products/combos/$comboId',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedProductsCombosNewRoute = AuthedProductsCombosNewRouteImport.update({
  id: '/products/combos/new',
  path: '/products/combos/new',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/attendance': typeof AuthedAttendanceRoute
  '/devices': typeof AuthedDevicesRoute
  '/members': typeof AuthedMembersRoute
  '/plans': typeof AuthedPlansRoute
  '/settings': typeof AuthedSettingsRoute
  '/transactions': typeof AuthedTransactionsRoute
  '/workers': typeof AuthedWorkersRoute
  '/inventory/history': typeof AuthedInventoryHistoryRoute
  '/inventory/suppliers': typeof AuthedInventorySuppliersRoute
  '/orders/new': typeof AuthedOrdersNewRoute
  '/products/ingredients': typeof AuthedProductsIngredientsRoute
  '/inventory/': typeof AuthedInventoryIndexRoute
  '/orders/': typeof AuthedOrdersIndexRoute
  '/products/': typeof AuthedProductsIndexRoute
  '/products/combos/$comboId': typeof AuthedProductsCombosComboIdRoute
  '/products/combos/new': typeof AuthedProductsCombosNewRoute
  '/products/combos/': typeof AuthedProductsCombosIndexRoute
}
export interface FileRoutesByTo {
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/attendance': typeof AuthedAttendanceRoute
  '/devices': typeof AuthedDevicesRoute
  '/members': typeof AuthedMembersRoute
  '/plans': typeof AuthedPlansRoute
  '/settings': typeof AuthedSettingsRoute
  '/transactions': typeof AuthedTransactionsRoute
  '/workers': typeof AuthedWorkersRoute
  '/': typeof AuthedIndexRoute
  '/inventory/history': typeof AuthedInventoryHistoryRoute
  '/inventory/suppliers': typeof AuthedInventorySuppliersRoute
  '/orders/new': typeof AuthedOrdersNewRoute
  '/products/ingredients': typeof AuthedProductsIngredientsRoute
  '/inventory': typeof AuthedInventoryIndexRoute
  '/orders': typeof AuthedOrdersIndexRoute
  '/products': typeof AuthedProductsIndexRoute
  '/products/combos/$comboId': typeof AuthedProductsCombosComboIdRoute
  '/products/combos/new': typeof AuthedProductsCombosNewRoute
  '/products/combos': typeof AuthedProductsCombosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/_authed/attendance': typeof AuthedAttendanceRoute
  '/_authed/devices': typeof AuthedDevicesRoute
  '/_authed/members': typeof AuthedMembersRoute
  '/_authed/plans': typeof AuthedPlansRoute
  '/_authed/settings': typeof AuthedSettingsRoute
  '/_authed/transactions': typeof AuthedTransactionsRoute
  '/_authed/workers': typeof AuthedWorkersRoute
  '/_authed/': typeof AuthedIndexRoute
  '/_authed/inventory/history': typeof AuthedInventoryHistoryRoute
  '/_authed/inventory/suppliers': typeof AuthedInventorySuppliersRoute
  '/_authed/orders/new': typeof AuthedOrdersNewRoute
  '/_authed/products/ingredients': typeof AuthedProductsIngredientsRoute
  '/_authed/inventory/': typeof AuthedInventoryIndexRoute
  '/_authed/orders/': typeof AuthedOrdersIndexRoute
  '/_authed/products/': typeof AuthedProductsIndexRoute
  '/_authed/products/combos/$comboId': typeof AuthedProductsCombosComboIdRoute
  '/_authed/products/combos/new': typeof AuthedProductsCombosNewRoute
  '/_authed/products/combos/': typeof AuthedProductsCombosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/attendance'
    | '/devices'
    | '/members'
    | '/plans'
    | '/settings'
    | '/transactions'
    | '/workers'
    | '/inventory/history'
    | '/inventory/suppliers'
    | '/orders/new'
    | '/products/ingredients'
    | '/inventory/'
    | '/orders/'
    | '/products/'
    | '/products/combos/$comboId'
    | '/products/combos/new'
    | '/products/combos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/sign-in'
    | '/sign-up'
    | '/attendance'
    | '/devices'
    | '/members'
    | '/plans'
    | '/settings'
    | '/transactions'
    | '/workers'
    | '/'
    | '/inventory/history'
    | '/inventory/suppliers'
    | '/orders/new'
    | '/products/ingredients'
    | '/inventory'
    | '/orders'
    | '/products'
    | '/products/combos/$comboId'
    | '/products/combos/new'
    | '/products/combos'
  id:
    | '__root__'
    | '/_authed'
    | '/sign-in'
    | '/sign-up'
    | '/_authed/attendance'
    | '/_authed/devices'
    | '/_authed/members'
    | '/_authed/plans'
    | '/_authed/settings'
    | '/_authed/transactions'
    | '/_authed/workers'
    | '/_authed/'
    | '/_authed/inventory/history'
    | '/_authed/inventory/suppliers'
    | '/_authed/orders/new'
    | '/_authed/products/ingredients'
    | '/_authed/inventory/'
    | '/_authed/orders/'
    | '/_authed/products/'
    | '/_authed/products/combos/$comboId'
    | '/_authed/products/combos/new'
    | '/_authed/products/combos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/attendance': {
      id: '/_authed/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AuthedAttendanceRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/devices': {
      id: '/_authed/devices'
      path: '/devices'
      fullPath: '/devices'
      preLoaderRoute: typeof AuthedDevicesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/members': {
      id: '/_authed/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof AuthedMembersRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/plans': {
      id: '/_authed/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof AuthedPlansRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings': {
      id: '/_authed/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthedSettingsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/transactions': {
      id: '/_authed/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof AuthedTransactionsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/workers': {
      id: '/_authed/workers'
      path: '/workers'
      fullPath: '/workers'
      preLoaderRoute: typeof AuthedWorkersRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/inventory/': {
      id: '/_authed/inventory/'
      path: '/inventory'
      fullPath: '/inventory/'
      preLoaderRoute: typeof AuthedInventoryIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/inventory/history': {
      id: '/_authed/inventory/history'
      path: '/inventory/history'
      fullPath: '/inventory/history'
      preLoaderRoute: typeof AuthedInventoryHistoryRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/inventory/suppliers': {
      id: '/_authed/inventory/suppliers'
      path: '/inventory/suppliers'
      fullPath: '/inventory/suppliers'
      preLoaderRoute: typeof AuthedInventorySuppliersRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/orders/': {
      id: '/_authed/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof AuthedOrdersIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/orders/new': {
      id: '/_authed/orders/new'
      path: '/orders/new'
      fullPath: '/orders/new'
      preLoaderRoute: typeof AuthedOrdersNewRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/products/': {
      id: '/_authed/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof AuthedProductsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/products/ingredients': {
      id: '/_authed/products/ingredients'
      path: '/products/ingredients'
      fullPath: '/products/ingredients'
      preLoaderRoute: typeof AuthedProductsIngredientsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/products/combos/': {
      id: '/_authed/products/combos/'
      path: '/products/combos'
      fullPath: '/products/combos/'
      preLoaderRoute: typeof AuthedProductsCombosIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/products/combos/$comboId': {
      id: '/_authed/products/combos/$comboId'
      path: '/products/combos/$comboId'
      fullPath: '/products/combos/$comboId'
      preLoaderRoute: typeof AuthedProductsCombosComboIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/products/combos/new': {
      id: '/_authed/products/combos/new'
      path: '/products/combos/new'
      fullPath: '/products/combos/new'
      preLoaderRoute: typeof AuthedProductsCombosNewRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedAttendanceRoute: typeof AuthedAttendanceRoute
  AuthedDevicesRoute: typeof AuthedDevicesRoute
  AuthedMembersRoute: typeof AuthedMembersRoute
  AuthedPlansRoute: typeof AuthedPlansRoute
  AuthedSettingsRoute: typeof AuthedSettingsRoute
  AuthedTransactionsRoute: typeof AuthedTransactionsRoute
  AuthedWorkersRoute: typeof AuthedWorkersRoute
  AuthedIndexRoute: typeof AuthedIndexRoute
  AuthedInventoryHistoryRoute: typeof AuthedInventoryHistoryRoute
  AuthedInventorySuppliersRoute: typeof AuthedInventorySuppliersRoute
  AuthedOrdersNewRoute: typeof AuthedOrdersNewRoute
  AuthedProductsIngredientsRoute: typeof AuthedProductsIngredientsRoute
  AuthedInventoryIndexRoute: typeof AuthedInventoryIndexRoute
  AuthedOrdersIndexRoute: typeof AuthedOrdersIndexRoute
  AuthedProductsIndexRoute: typeof AuthedProductsIndexRoute
  AuthedProductsCombosComboIdRoute: typeof AuthedProductsCombosComboIdRoute
  AuthedProductsCombosNewRoute: typeof AuthedProductsCombosNewRoute
  AuthedProductsCombosIndexRoute: typeof AuthedProductsCombosIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedAttendanceRoute: AuthedAttendanceRoute,
  AuthedDevicesRoute: AuthedDevicesRoute,
  AuthedMembersRoute: AuthedMembersRoute,
  AuthedPlansRoute: AuthedPlansRoute,
  AuthedSettingsRoute: AuthedSettingsRoute,
  AuthedTransactionsRoute: AuthedTransactionsRoute,
  AuthedWorkersRoute: AuthedWorkersRoute,
  AuthedIndexRoute: AuthedIndexRoute,
  AuthedInventoryHistoryRoute: AuthedInventoryHistoryRoute,
  AuthedInventorySuppliersRoute: AuthedInventorySuppliersRoute,
  AuthedOrdersNewRoute: AuthedOrdersNewRoute,
  AuthedProductsIngredientsRoute: AuthedProductsIngredientsRoute,
  AuthedInventoryIndexRoute: AuthedInventoryIndexRoute,
  AuthedOrdersIndexRoute: AuthedOrdersIndexRoute,
  AuthedProductsIndexRoute: AuthedProductsIndexRoute,
  AuthedProductsCombosComboIdRoute: AuthedProductsCombosComboIdRoute,
  AuthedProductsCombosNewRoute: AuthedProductsCombosNewRoute,
  AuthedProductsCombosIndexRoute: AuthedProductsCombosIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
